# Generated by Django 3.2.9 on 2021-12-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, upload_to='')),
                ('caracteristicas', models.TextField()),
                ('voltage', models.IntegerField(blank=True, null=True)),
                ('potencia', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
