# Generated by Django 3.2.9 on 2021-12-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
