# Generated by Django 3.2.9 on 2021-12-10 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_auto_20211210_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='partes',
            name='costo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partes',
            name='equipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='equipment.equipment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partes',
            name='proveedor',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partes',
            name='subsistema',
            field=models.CharField(choices=[('ELECTRICO', 'electrico'), ('HIDRAULICO', 'hidraulico'), ('NEUMATICO', 'neumatico'), ('CONTROL', 'control')], default='ELECTRICO', max_length=20),
        ),
        migrations.AlterField(
            model_name='partes',
            name='caracteristicas',
            field=models.TextField(max_length=1500),
        ),
    ]
