# Generated by Django 3.2.9 on 2021-12-10 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_auto_20211210_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partes',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='equipment.equipment'),
        ),
        migrations.AlterField(
            model_name='partes',
            name='proveedor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
