# Generated by Django 3.2.9 on 2021-12-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_auto_20211210_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('frecuencia', models.IntegerField()),
                ('descripción', models.TextField()),
                ('tiempo_Extimado', models.IntegerField()),
                ('ult_Fecha', models.DateField()),
                ('prox_Fecha', models.DateField(auto_now_add=True)),
                ('anexos', models.FileField(blank=True, null=True, upload_to='')),
                ('partes', models.ManyToManyField(to='equipment.Equipment')),
            ],
        ),
    ]
