# Generated by Django 3.2.9 on 2021-12-10 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_alter_actividade_tiempo_extimado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte_Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('reporte', models.TextField()),
                ('responsable', models.CharField(blank=True, max_length=50, null=True)),
                ('costos_adicionales', models.IntegerField()),
                ('nota_costos', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('tipo_mantenimiento', models.CharField(choices=[('PREVENTIVO', 'epreventivo'), ('CORREPTIVO', 'correctivo')], default='PREVENTIVO', max_length=20)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='equipment.actividade')),
            ],
        ),
    ]
