# Generated by Django 3.2.9 on 2021-12-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_reporte_actividades'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reporte_Actividades',
            new_name='Reporte_Actividade',
        ),
    ]
