# Generated by Django 3.2.9 on 2021-12-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_rename_reporte_actividades_reporte_actividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte_actividade',
            name='costos_adicionales',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporte_actividade',
            name='nota_costos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
