# Generated by Django 3.2.9 on 2021-12-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_auto_20211210_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte_actividade',
            name='tipo_mantenimiento',
            field=models.CharField(choices=[('PREVENTIVO', 'preventivo'), ('CORRECTIVO', 'correctivo')], default='PREVENTIVO', max_length=20),
        ),
    ]
