# Generated by Django 3.2.9 on 2021-12-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0013_alter_reporte_actividade_tipo_mantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
