# Generated by Django 3.2.9 on 2021-12-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0014_alter_equipment_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='caracteristicas',
            field=models.TextField(verbose_name='Caracteristicas'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
