# Generated by Django 3.2.9 on 2021-12-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0015_auto_20211215_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partes',
            name='costo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
