# Generated by Django 3.2.9 on 2021-12-20 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0016_alter_partes_costo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividade',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='actividade',
            old_name='tiempo_Extimado',
            new_name='tiempo_estimado',
        ),
        migrations.RemoveField(
            model_name='actividade',
            name='partes',
        ),
        migrations.AddField(
            model_name='actividade',
            name='partes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='equipment.partes'),
        ),
    ]
