# Generated by Django 3.2.9 on 2022-01-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0017_auto_20211220_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte_actividade',
            name='tipo_mantenimiento',
            field=models.CharField(choices=[('PREVENTIVO', 'PREVENTIVO'), ('CORRECTIVO', 'CORRECTIVO')], default='PREVENTIVO', max_length=20),
        ),
    ]
