# Generated by Django 3.2.9 on 2022-01-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0018_alter_reporte_actividade_tipo_mantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='partes',
            name='Unidades',
            field=models.CharField(choices=[('CENTIMETROS', 'centimetros'), ('GRAMOS', 'gramos'), ('LITROS', 'litros'), ('METROS', 'metros'), ('UNIDADES', 'unidades')], default='---', max_length=20),
        ),
        migrations.AlterField(
            model_name='actividade',
            name='frecuencia',
            field=models.FloatField(),
        ),
    ]
