# Generated by Django 3.2.9 on 2022-01-25 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0019_auto_20220125_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividade',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='equipment.equipment'),
        ),
    ]
