# Generated by Django 3.2.9 on 2022-01-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0021_alter_partes_unidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividade',
            name='cantidad',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividade',
            name='tiempo_estimado',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
