# Generated by Django 3.2.9 on 2022-01-26 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0023_alter_actividade_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='caracteristicas',
        ),
    ]
