# Generated by Django 3.2.9 on 2022-01-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0024_remove_equipment_caracteristicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='caracteristicas',
            field=models.TextField(default=1, verbose_name='Caracteristicas'),
            preserve_default=False,
        ),
    ]
