# Generated by Django 3.2.9 on 2022-01-28 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0025_equipment_caracteristicas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['-nombre']},
        ),
    ]
