# Generated by Django 3.2.9 on 2022-02-04 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0028_auto_20220203_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partes',
            options={'ordering': ['-nombre']},
        ),
        migrations.RemoveField(
            model_name='actividades',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='actividades',
            name='partes',
        ),
        migrations.RemoveField(
            model_name='partes',
            name='equipo',
        ),
        migrations.AddField(
            model_name='partes',
            name='equipo',
            field=models.ManyToManyField(blank=True, null=True, to='equipment.Equipment'),
        ),
        migrations.CreateModel(
            name='PartsQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=1)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='equipment.actividades')),
                ('partes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='equipment.partes')),
            ],
        ),
        migrations.AddField(
            model_name='actividades',
            name='partes',
            field=models.ManyToManyField(through='equipment.PartsQuantity', to='equipment.Partes'),
        ),
    ]
