# Generated by Django 3.2.9 on 2022-02-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0029_auto_20220204_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partsquantity',
            old_name='partes',
            new_name='parte',
        ),
        migrations.AlterField(
            model_name='actividades',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='ult_Fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='partes',
            name='equipo',
            field=models.ManyToManyField(blank=True, null=True, to='equipment.Equipment'),
        ),
    ]
