# Generated by Django 3.2.9 on 2022-02-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0030_auto_20220204_0832'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actividades',
            new_name='Activities',
        ),
        migrations.RenameModel(
            old_name='Reporte_Actividades',
            new_name='Activities_Report',
        ),
        migrations.RenameModel(
            old_name='Partes',
            new_name='Parts',
        ),
        migrations.AlterField(
            model_name='parts',
            name='equipo',
            field=models.ManyToManyField(blank=True, null=True, to='equipment.Equipment'),
        ),
    ]
