# Generated by Django 3.2.9 on 2022-02-08 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0031_auto_20220204_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='equipo',
            field=models.ManyToManyField(blank=True, null=True, to='equipment.Equipment'),
        ),
        migrations.AlterField(
            model_name='partsquantity',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.activities'),
        ),
        migrations.AlterField(
            model_name='partsquantity',
            name='parte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.parts'),
        ),
    ]
