# Generated by Django 3.2.9 on 2022-02-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0033_auto_20220210_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partsquantity',
            name='equipo',
        ),
        migrations.AlterField(
            model_name='parts',
            name='equipo',
            field=models.ManyToManyField(blank=True, null=True, to='equipment.Equipment'),
        ),
    ]
