# Generated by Django 3.2.9 on 2022-02-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0034_auto_20220211_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parts',
            old_name='Unidades',
            new_name='unidades',
        ),
        migrations.AlterField(
            model_name='parts',
            name='equipo',
            field=models.ManyToManyField(blank=True, null=True, to='equipment.Equipment'),
        ),
    ]
