# Generated by Django 4.0.2 on 2022-03-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0036_alter_parts_subsistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activities',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='parts',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
