# Generated by Django 4.0.2 on 2022-04-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0037_activities_finalizado_alter_activities_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={'ordering': ['-nombre']},
        ),
        migrations.RemoveField(
            model_name='activities_report',
            name='actividad',
        ),
        migrations.AddField(
            model_name='activities_report',
            name='actividad',
            field=models.ManyToManyField(blank=True, to='equipment.Activities'),
        ),
    ]
