# Generated by Django 4.0.2 on 2022-04-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0038_alter_activities_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='equipo',
            field=models.ManyToManyField(blank=True, to='equipment.Equipment'),
        ),
    ]
